services:
  db_igma:
    image: postgres
    container_name: db_igma
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg_igma:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db_igma
    env_file:
      - .env

volumes:
  pg_igma:
